AWSTemplateFormatVersion: "2010-09-09"
Description: "Supplemental stack for Redshift Immersion Day labs 11, 12, and 18"
Parameters:
  RedshiftSubnetA:
    Description: First Redshift Subnet
    Type: AWS::EC2::Subnet::Id
  RedshiftSubnetB:
    Description: Second Redshift Subnet
    Type: AWS::EC2::Subnet::Id
  RedshiftSecurityGroup:
    Description: Redshift Security Group ID
    Type: AWS::EC2::SecurityGroup::Id
Mappings:
  RegionMap:
    us-west-2: # Oregon
      "EC2AMI" : "ami-03d1fabac69d3be74"
    us-east-1: # Virginia
      "EC2AMI" : "ami-0ef97a8d5328f468e"
Resources:
  SSMSessionManagerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: RSDD-SessionManagerRole-CF
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
  SSMSessionManagerPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: RSDD-SessionManagerPermissions-CF
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ssm:UpdateInstanceInformation"
              - "ssmmessages:CreateControlChannel"
              - "ssmmessages:CreateDataChannel"
              - "ssmmessages:OpenControlChannel"
              - "ssmmessages:OpenDataChannel"
              - "s3:GetEncryptionConfiguration"
            Resource: '*'
      Roles:
        - !Ref SSMSessionManagerRole
  LambdaRoleToInitDMS:
    Type: AWS::IAM::Role
    Properties :
      AssumeRolePolicyDocument:
        Version : 2012-10-17
        Statement :
          -
            Effect : Allow
            Principal :
              Service :
                - lambda.amazonaws.com
            Action :
              - sts:AssumeRole
      Path : /
      Policies:
        -
          PolicyName: LambdaCloudFormationPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Sub "arn:aws:s3:::cloudformation-custom-resource-response-${AWS::Region}"
                  - !Sub "arn:aws:s3:::cloudformation-waitcondition-${AWS::Region}"
                  - !Sub "arn:aws:s3:::cloudformation-custom-resource-response-${AWS::Region}/*"
                  - !Sub "arn:aws:s3:::cloudformation-waitcondition-${AWS::Region}/*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonRDSDataFullAccess
        - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/AmazonRedshiftFullAccess
  LambdaFunctionDMSRoles:
    Type: "AWS::Lambda::Function"
    Properties:
      Timeout: 30
      Code:
        ZipFile: |
          import json
          import boto3
          import cfnresponse
          import logging
          import time
          client = boto3.client('iam')
          logging.basicConfig()
          logger = logging.getLogger(__name__)
          logger.setLevel(logging.INFO)

          def handler(event, context):
            logger.info(json.dumps(event))

            if event['RequestType'] == 'Delete':
              cfnresponse.send(event, context, cfnresponse.SUCCESS, {'Data': 'Delete complete'})
            else:
              try:
                response = client.get_role(RoleName='dms-access-for-endpoint')
              except:
                try:
                  role_policy_document = {
                      "Version": "2012-10-17",
                      "Statement": [
                        {
                          "Effect": "Allow",
                          "Principal": {
                            "Service": [
                              "dms.amazonaws.com",
                              "redshift.amazonaws.com"
                            ]
                          },
                          "Action": "sts:AssumeRole"
                        }
                      ]
                  }
                  client.create_role(
                      RoleName='dms-access-for-endpoint',
                      AssumeRolePolicyDocument=json.dumps(role_policy_document)
                  )
                  client.attach_role_policy(
                    RoleName='dms-access-for-endpoint',
                    PolicyArn='arn:aws:iam::aws:policy/service-role/AmazonDMSRedshiftS3Role'
                  )
                except Exception as e:
                  logger.error(e)
                  cfnresponse.send(event, context, cfnresponse.FAILED, {'Data': 'Create failed'})
              try:
                response = client.get_role(RoleName='dms-cloudwatch-logs-role')
              except:
                try:
                  role_policy_document = {
                      "Version": "2012-10-17",
                      "Statement": [
                        {
                          "Effect": "Allow",
                          "Principal": {
                            "Service": [
                              "dms.amazonaws.com"
                            ]
                          },
                          "Action": "sts:AssumeRole"
                        }
                      ]
                  }
                  client.create_role(
                      RoleName='dms-cloudwatch-logs-role',
                      AssumeRolePolicyDocument=json.dumps(role_policy_document)
                  )
                  client.attach_role_policy(
                    RoleName='dms-cloudwatch-logs-role',
                    PolicyArn='arn:aws:iam::aws:policy/service-role/AmazonDMSCloudWatchLogsRole'
                  )
                except Exception as e:
                  logger.error(e)
                  cfnresponse.send(event, context, cfnresponse.FAILED, {'Data': 'Create failed'})
              try:
                response = client.get_role(RoleName='dms-vpc-role')
              except:
                try:
                  role_policy_document = {
                      "Version": "2012-10-17",
                      "Statement": [
                        {
                          "Effect": "Allow",
                          "Principal": {
                            "Service": [
                              "dms.amazonaws.com"
                            ]
                          },
                          "Action": "sts:AssumeRole"
                        }
                      ]
                  }
                  client.create_role(
                      RoleName='dms-vpc-role',
                      AssumeRolePolicyDocument=json.dumps(role_policy_document)
                  )
                  client.attach_role_policy(
                    RoleName='dms-vpc-role',
                    PolicyArn='arn:aws:iam::aws:policy/service-role/AmazonDMSVPCManagementRole'
                  )
                  time.sleep(30)
                except Exception as e:
                  logger.error(e)
                  cfnresponse.send(event, context, cfnresponse.FAILED, {'Data': 'Create failed'})

              cfnresponse.send(event, context, cfnresponse.SUCCESS, {'Data': 'Create complete'})
      Handler: index.handler
      Role:
        Fn::GetAtt: [LambdaRoleToInitDMS, Arn]
      Runtime: python3.7
  InitDMSRoles:
     Type: Custom::InitDMSRoles
     DependsOn:
       - LambdaFunctionDMSRoles
     Properties:
       ServiceToken: !GetAtt 'LambdaFunctionDMSRoles.Arn'
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref SSMSessionManagerRole
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 'm5a.xlarge'
      SecurityGroupIds: [!Ref 'RedshiftSecurityGroup']
      IamInstanceProfile:
        !Ref EC2InstanceProfile
      SubnetId:
        Ref: RedshiftSubnetA
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            DeleteOnTermination: 'true'
            Iops: '2000'
            VolumeSize: '250'
            VolumeType: io1
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - EC2AMI
      UserData:
          Fn::Base64:
            !Sub |
              <powershell>
               new-item 'c:\users\developer\initialize.log'
              $log = 'c:\users\developer\initialize.log'
              $now = Get-Date
              try {
                  Add-Content $log -value "[$now] - setting developer password and granting remote login"
                  net.exe user developer Password1
                  net.exe LOCALGROUP "Remote Desktop Users" developer /ADD
                  Add-Content $log -value "[$now] - successfully set password to Password1"
              } catch {
                  Add-Content $log -value "[$now] - error changing password $_"
              }
              Add-Content $log -value "[$now] - updating SSM agent..."
              try {
                $progressPreference = 'silentlyContinue'
                Add-Content $log -value "[$now] - downloading SSM agent..."
                Invoke-WebRequest 'https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/windows_amd64/AmazonSSMAgentSetup.exe' -OutFile 'c:\Windows\Temp\SSMAgent_latest.exe'
                Add-Content $log -value "[$now] - installing SSM agent..."
                Start-Process -FilePath 'c:\Windows\Temp\SSMAgent_latest.exe' -ArgumentList "/S"
                Add-Content $log -value "[$now] - restarting SSM agent..."
                Restart-Service AmazonSSMAgent
                Add-Content $log -value "[$now] - successfully updated SSM agent"
              } catch {
                Add-Content $log -value "[$now] - error updating SSM agent"
              }
              </powershell>
  DMSInstanceSubnetGroup:
    Type: AWS::DMS::ReplicationSubnetGroup
    DependsOn:
      - InitDMSRoles
    Properties:
      ReplicationSubnetGroupDescription: DMS Subnet Group
      SubnetIds:
        - Ref: RedshiftSubnetA
        - Ref: RedshiftSubnetB
  DMSInstance:
    Type: AWS::DMS::ReplicationInstance
    Properties:
      AllocatedStorage: 100
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      MultiAZ: false
      PubliclyAccessible: true
      ReplicationInstanceClass: 'dms.c4.xlarge'
      ReplicationSubnetGroupIdentifier: !Ref DMSInstanceSubnetGroup
      VpcSecurityGroupIds:
        - Ref: RedshiftSecurityGroup
Outputs:
  EC2Hostname:
    Description: Public DNS endpoint for the EC2 instance
    Value:
      Fn::GetAtt:
      - EC2Instance
      - PublicDnsName
